// module: techData
// deps: {}
module.exports = {};
const __mod = function(e, t, i) {
        "use strict";
        (cc._RF.push(t, "138d1iRXu1Jmo0PhY8WF8m/", "techData"), Object.defineProperty(i, "__esModule", {
            value: !0
          }),
          (i.default = [{
            id: 1,
            category: "基地",
            unlock_level: 0,
            name: "强化防御",
            description: "基地受到伤害-$n%",
            value_range: [10, 30],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 2,
            category: "基地",
            unlock_level: 0,
            name: "强化攻击",
            description: "基地攻击力+$n%",
            value_range: [10, 30],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 3,
            category: "基地",
            unlock_level: 0,
            name: "强化农民",
            description: "农民血量+$n%",
            value_range: [20, 100],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 4,
            category: "基地",
            unlock_level: 10,
            name: "指挥中心",
            description: "我方全场单位防御+$n%",
            value_range: [10, 20],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 5,
            category: "基地",
            unlock_level: 10,
            name: "战略中心",
            description: "我方全场单位伤害+$n%",
            value_range: [10, 20],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 6,
            category: "基地",
            unlock_level: 10,
            name: "精英培育",
            description: "生产农民时有$n%概率出现高效的精英农民",
            value_range: [10, 20],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 7,
            category: "基地",
            unlock_level: 15,
            name: "修复强化",
            description: "修复技能额外附加免疫伤害效果，持续$n秒。",
            value_range: [2, 4],
            value_range2: null,
            prerequisite_tech: "4",
          }, {
            id: 8,
            category: "基地",
            unlock_level: 15,
            name: "核能强化",
            description: "核弹伤害+$n%。",
            value_range: [10, 50],
            value_range2: null,
            prerequisite_tech: "5",
          }, {
            id: 9,
            category: "基地",
            unlock_level: 15,
            name: "维修",
            description: "基地受损后，每存在一个农民可修复基地$n%/秒的血量",
            value_range: [0.6, 1],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 10,
            category: "兵营",
            unlock_level: 0,
            name: "精准",
            description: "机枪兵对隐身单位命中和伤害+$n%",
            value_range: [10, 30],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 11,
            category: "兵营",
            unlock_level: 0,
            name: "燃烧",
            description: "喷火兵可点燃目标，每0.5秒造成$n%的伤害，持续2秒",
            value_range: [10, 50],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 12,
            category: "兵营",
            unlock_level: 0,
            name: "远程防御",
            description: "护盾兵受到远程伤害-$n%",
            value_range: [10, 30],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 13,
            category: "兵营",
            unlock_level: 10,
            name: "合纵",
            description: "攻击同目标的机枪兵数量越多，攻击力越高，最多+$n%",
            value_range: [10, 50],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 14,
            category: "兵营",
            unlock_level: 10,
            name: "贯穿喷射",
            description: "喷火兵攻击可穿透目标对其身后单位造成$n%伤害",
            value_range: [60, 100],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 15,
            category: "兵营",
            unlock_level: 10,
            name: "自疗",
            description: "护盾兵恢复自身$n%/秒的血量",
            value_range: [5, 9],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 16,
            category: "兵营",
            unlock_level: 15,
            name: "强化针",
            description: "机枪兵的攻击、攻速和移速+100%，但受到伤害+$n%",
            value_range: [50, 20],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 17,
            category: "兵营",
            unlock_level: 15,
            name: "自爆",
            description: "喷火兵死亡时冲向目标自爆，造成$n%范围伤害",
            value_range: [100, 200],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 18,
            category: "兵营",
            unlock_level: 15,
            name: "群体医疗",
            description: "护盾兵恢复周围人型单位$n%/秒的血量，无法叠加",
            value_range: [2, 4],
            value_range2: null,
            prerequisite_tech: "15",
          }, {
            id: 19,
            category: "重工",
            unlock_level: 0,
            name: "凝滞",
            description: "冰雷车降低非boss单位$n%攻、移速，持续3秒",
            value_range: [10, 50],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 20,
            category: "重工",
            unlock_level: 0,
            name: "压制",
            description: "坦克对中型单位造成伤害+$n%",
            value_range: [5, 25],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 21,
            category: "重工",
            unlock_level: 0,
            name: "双枪",
            description: "机器人攻击目标+1，但攻击力-$n%",
            value_range: [60, 30],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 22,
            category: "重工",
            unlock_level: 10,
            name: "机动",
            description: "冰雷车优先攻击离基地最近单位，且闪避+$n%",
            value_range: [10, 30],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 23,
            category: "重工",
            unlock_level: 10,
            name: "重甲防护",
            description: "坦克受到小型单位的伤害-$n%",
            value_range: [10, 30],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 24,
            category: "重工",
            unlock_level: 10,
            name: "坚毅",
            description: "机器人被摧毁后会在原地继续攻击，持续$n秒",
            value_range: [2, 4],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 25,
            category: "重工",
            unlock_level: 15,
            name: "强化冰雷",
            description: "冰雷车攻击5次后释放强化冰雷，造成$n%范围伤害，附加冻效果",
            value_range: [60, 100],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 26,
            category: "重工",
            unlock_level: 15,
            name: "高射炮",
            description: "坦克的伤害、伤害范围、射程+$n%，但移速-30%",
            value_range: [10, 30],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 27,
            category: "重工",
            unlock_level: 15,
            name: "地空导弹",
            description: "机器人每秒额外对射程内的一个空中单位造成$n%伤害",
            value_range: [40, 80],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 28,
            category: "机场",
            unlock_level: 0,
            name: "射程",
            description: "战机射程+$n%，对空效果翻倍",
            value_range: [10, 30],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 29,
            category: "机场",
            unlock_level: 0,
            name: "防护罩",
            description: "科技球随机提升周围某个单位$n%的防御",
            value_range: [10, 30],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 30,
            category: "机场",
            unlock_level: 0,
            name: "重打击",
            description: "大和舰对大型单位的伤害+$n%",
            value_range: [5, 25],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 31,
            category: "机场",
            unlock_level: 10,
            name: "制空",
            description: "战机将优先攻击空中单位，且对空伤害+$n%",
            value_range: [5, 25],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 32,
            category: "机场",
            unlock_level: 10,
            name: "辐射弹",
            description: "科技球每5秒释放辐射弹，造成$n%范围伤害，对小型目标效果翻倍",
            value_range: [60, 100],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 33,
            category: "机场",
            unlock_level: 10,
            name: "连射",
            description: "大和舰有$n%概率额外攻击一次，但第二次攻击伤害-50%",
            value_range: [10, 20],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 34,
            category: "机场",
            unlock_level: 15,
            name: "隐身",
            description: "战机开启隐身模式，产生对地$n%和对空$m%的躲避效果",
            value_range: [30, 60],
            value_range2: [15, 35],
            prerequisite_tech: null,
          }, {
            id: 35,
            category: "机场",
            unlock_level: 15,
            name: "EMP冲击",
            description: "科技球优先攻击范围内boss单位，并削弱其$n%防御",
            value_range: [10, 20],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 36,
            category: "机场",
            unlock_level: 15,
            name: "大和炮",
            description: "大和舰攻击5次后发射大和炮，秒杀非boss单位，对boss造成$n%伤害，仅1次",
            value_range: [200, 500],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 37,
            category: "炮塔",
            unlock_level: 0,
            name: "射程",
            description: "炮塔的射程+$n%",
            value_range: [10, 30],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 38,
            category: "炮塔",
            unlock_level: 0,
            name: "射速",
            description: "炮塔的射击速度+$n%",
            value_range: [10, 30],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 39,
            category: "炮塔",
            unlock_level: 10,
            name: "多重弹",
            description: "炮塔同时发射两枚导弹，但攻击力-$n%",
            value_range: [50, 30],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 40,
            category: "炮塔",
            unlock_level: 10,
            name: "穿甲弹",
            description: "炮塔的攻击可贯穿目标，对其后方目标造成$n%伤害",
            value_range: [60, 100],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 41,
            category: "炮塔",
            unlock_level: 15,
            name: "战时修复",
            description: "炮塔被摧毁$n秒后恢复50%生命值继续战斗，仅1次",
            value_range: [8, 4],
            value_range2: null,
            prerequisite_tech: null,
          }, {
            id: 42,
            category: "炮塔",
            unlock_level: 15,
            name: "震荡波",
            description: "炮塔被摧毁时对周围敌人造成$n%伤害，并击退，仅1次",
            value_range: [100, 200],
            value_range2: null,
            prerequisite_tech: null,
          }, ]), cc._RF.pop());
      };
